source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target ’SampleList’ do
pod 'Alamofire', '~> 4.6'
pod 'AlamofireImage', '~> 3.3'
pod 'SwiftyJSON'
pod 'SVProgressHUD'

end

target ’SampleListTests’ do
    pod 'Alamofire', '~> 4.6'
    pod 'AlamofireImage', '~> 3.3'
    pod 'SwiftyJSON'
    pod 'SVProgressHUD'

end
